-- EchoMe Phase 1 schema.
--
-- THE RULE: no table here stores conversation text in readable form. The only
-- place a transcript exists at rest is live_sessions.encrypted_payload, as
-- AES-256-GCM ciphertext under a key that belongs to that one session.
--
-- Deliberately absent: any messages / chat_history / conversations /
-- transcripts table. If a future migration proposes one, it is wrong.

-- ---------------------------------------------------------------------------
-- profiles
-- ---------------------------------------------------------------------------

create table public.profiles (
  id           uuid primary key references auth.users (id) on delete cascade,
  email        text not null,
  display_name text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

comment on table public.profiles is
  'One row per auth user. Never holds conversation content.';

alter table public.profiles enable row level security;

create policy "profiles: read own"
  on public.profiles for select
  to authenticated
  using (auth.uid() = id);

create policy "profiles: update own"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- No insert or delete policy. Rows appear via the trigger below and disappear
-- with the auth user.

-- Profile creation is a trigger rather than app code, so a profile cannot go
-- missing because a signup handler failed halfway.
create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- live_sessions
-- ---------------------------------------------------------------------------

create type public.session_status as enum ('open', 'closing', 'closed');

create table public.live_sessions (
  id                uuid primary key,
  user_id           uuid not null references auth.users (id) on delete cascade,
  status            public.session_status not null default 'open',
  created_at        timestamptz not null default now(),
  last_active_at    timestamptz not null default now(),
  encrypted_payload bytea not null,
  wrapped_key       bytea not null,
  nonce             bytea not null
);

comment on table public.live_sessions is
  'The in-flight conversation. encrypted_payload is AES-256-GCM ciphertext; '
  'wrapped_key is the per-session data key encrypted under SESSION_MASTER_KEY. '
  'Closing a session zeroes wrapped_key and deletes the row.';

comment on column public.live_sessions.id is
  'Generated by the application, not the database, because it is bound into the '
  'AES-GCM additional authenticated data.';

comment on column public.live_sessions.wrapped_key is
  'Layout: nonce(12) || ciphertext || tag(16). All-zero means destroyed.';

comment on column public.live_sessions.nonce is
  'GCM nonce for encrypted_payload only. Rotated on every save.';

-- A user has at most one open session. Closing sessions are excluded so a
-- future closing ritual can run while a new conversation starts.
create unique index live_sessions_one_open_per_user
  on public.live_sessions (user_id)
  where status = 'open';

create index live_sessions_idle
  on public.live_sessions (last_active_at)
  where status = 'open';

alter table public.live_sessions enable row level security;

-- Intentionally ZERO policies. With RLS on and no policy, neither the anon nor
-- the authenticated role can select, insert, update or delete a single row.
-- The table is reachable only through server route handlers on the service
-- role, which filter on user_id in every query. The ciphertext would be
-- harmless to expose; not exposing it is cheaper than reasoning about it.
revoke all on public.live_sessions from anon, authenticated;

-- ---------------------------------------------------------------------------
-- turn_telemetry
-- ---------------------------------------------------------------------------

create table public.turn_telemetry (
  id          bigserial primary key,
  user_id     uuid references auth.users (id) on delete set null,
  -- No foreign key to live_sessions on purpose: telemetry must outlive the
  -- session row it describes, and a cascade here would silently erase our only
  -- operational history the moment a conversation closes.
  session_id  uuid,
  created_at  timestamptz not null default now(),
  duration_ms integer not null,
  model       text,
  stop_reason text,
  error_class text,
  input_tokens                integer,
  output_tokens               integer,
  cache_read_input_tokens     integer,
  cache_creation_input_tokens integer
);

comment on table public.turn_telemetry is
  'Content-free. Durations, token counts, model and error class only. There is '
  'no column here that can hold user text, and adding one would be a bug.';

create index turn_telemetry_user_time
  on public.turn_telemetry (user_id, created_at desc);

alter table public.turn_telemetry enable row level security;
revoke all on public.turn_telemetry from anon, authenticated;
